#!/usr/bin/env sh

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
  lls="logo-ls" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias ka="killall" \
	mkd="mkdir -pv" \
	calcurse="calcurse -D ~/.config/calcurse" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
  ll="ls -l" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
  la="ls -la" \
  gcl="git clone" \
  start_endpoint="cd ~/work/endpoint/endpoints && python3 -m http.server 8000" \
  kbrw_tunnel="bash /home/charles/work/endpoint/bin/tunnels-start.sh cvignal qa" \
  sudo='sudo -A' \
  infra-cli='cd ~/work/chef-repo/tools/ && ./infra-cli' \
  wifiscan='nmcli device wifi rescan && nmcli device wifi list' \
  zpm='cd ~/work/zpm && java -jar release/1.6_no_rest_version/zpm.jar' \
  sshr='ssh -J access01.cloud.kbrwadventure.com'

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
