source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null

# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc"

export PATH=$PATH:$HOME/.local/share/cargo/bin
export KNIFE_HOME=$HOME/work/chef-repo/.chef
export CHEF_USER="cvignal"

() {
    for config_file (${ZDOTDIR:-/home/charles/.config/zsh}/rc/*.zsh) source $config_file
    [ ! -e $ZDOTDIR/env ] || . $ZSH/env
}

add-zsh-hook precmd _vbe_setprompt
